services:
  - type: web
    name: spam-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords
    startCommand: python app.py
    autoDeploy: true